language: node_js

node_js:
  - 'node'
  - '14'

#matrix:
#  fast_finish: true

#branches:
#  only:
#  - master
#  - /^release-.*/

#install:
#  - npm uninstall typescript --no-save
#  - npm ci

before_script:
  - npm install
  - npm install typescript --save-dev
  
script:
  - npm run compile
  - npm run test

cache:
  directories:
    - node_modules
